# Generated by Django 3.2.15 on 2022-10-15 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0044_alter_dataset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='file_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='intermediate_storage',
            field=models.CharField(blank=True, choices=[('GOOGLE_DRIVE', 'GOOGLE_DRIVE')], max_length=255, null=True, verbose_name='Intermediate Storage'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_collector_dataset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_data_collector',
            field=models.BooleanField(default=False, help_text='use data collector to populate this dataset', verbose_name='Use As Data Collector?'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='use_aggregate_data',
            field=models.BooleanField(default=False, help_text='syncronize this dataset from its data collector dataset', verbose_name='Sync Data From Data Collector'),
        ),
        migrations.CreateModel(
            name='UserCollectorStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('intermediate_dataset_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('folder', models.CharField(blank=True, max_length=200, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='user_collector',
            field=models.ManyToManyField(blank=True, through='layers.UserCollectorStorage', to=settings.AUTH_USER_MODEL),
        ),
    ]
