# Generated by Django 3.2.15 on 2023-10-17 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0045_auto_20221015_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('folder', models.CharField(blank=True, max_length=400, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]